#!/bin/bash

# BSD 3-Clause License
# 
# Copyright (c) 2019, michalkrzyz
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

HASH_COMMENT_FILES=`find -iname "CMakeLists.txt" -or -iname "*.sh" -or -iname "*.py"`
CSTYLE_COMMENT_FILES=`find -iname "*.h" -or -iname "*.hpp" -or -iname "*.cpp" -or -iname "*.c"`

TMPFILE=/tmp/LICENSEDFILE.tmp

cat_hash_comment_license_and_args()
{
  cat $PWD/LICENSE | sed 's@^@#@g'
  echo
  [ $# -gt 0 ] && cat $@
}

cat_cstyle_comment_license_and_args()
{
  cat $PWD/LICENSE | sed 's@^@//@g'
  echo
  [ $# -gt 0 ] && cat $@
}

for F in $HASH_COMMENT_FILES
do
  if head -n 1 $F | fgrep "# BSD" &> /dev/null
  then
    echo $F has license
  else
    echo $F has missing license ---------- Adding license header
    cat_hash_comment_license_and_args $F > $TMPFILE
    cp $TMPFILE $F
  fi
done

for F in $CSTYLE_COMMENT_FILES
do
  if head -n 1 $F | fgrep "// BSD" &> /dev/null
  then
    echo $F has license
  else
    echo $F has missing license ---------- Adding license header
    cat_cstyle_comment_license_and_args $F > $TMPFILE
    cp $TMPFILE $F
  fi
done
